// Generated by https://quicktype.io

export interface History {
  id: number;
  watched_at: string;
  action: string;
  type: string;
  movie: Movie;
}

export interface Movie {
  title: string;
  year: number;
  ids: IDS;
  tagline: string;
  overview: string;
  released: string;
  runtime: number;
  country: string;
  trailer: string;
  homepage: null | string;
  status: string;
  rating: number;
  votes: number;
  comment_count: number;
  updated_at: string;
  language: string;
  available_translations: string[];
  genres: string[];
  certification: string;
}

export interface IDS {
  trakt: number;
  slug: string;
  imdb: string;
  tmdb: number;
}
